var violationTypes = [
		{
		  "violation":"CouplingBetweenObjects",
		  "color":"Yellow"
		}, 
		{
		  "violation":"ExcessiveImports",
		  "color":"Fuchsia"
		}, 		
		{
	      "violation":"LooseCoupling",
		  "color":"Cyan"
		},		
		{
		  "violation":"LoosePackageCoupling",
		  "color":"Brown"
		},			
		{
		  "violation":"LawOfDemeter",
		  "color":"Green"
		}	
];