var violationTypes = [
                		{
                		  "violation":"UnnecessaryConstructor",
                		  "color":"Yellow"
                		}, 
                		{
                		  "violation":"NullAssignment",
                		  "color":"Fuchsia"
                		}, 		
                		{
                	      "violation":"OnlyOneReturn",
                		  "color":"Cyan"
                		},		
                		{
                		  "violation":"AssignmentInOperand",
                		  "color":"Brown"
                		},			
                		{
                		  "violation":"AtLeastOneConstructor",
                		  "color":"Green"
                		}, 
                		{
                		  "violation":"CallSuperInConstructor",
                		  "color":"#8B8F8B"
                		},			
                		{
                		  "violation":"UnnecessaryParentheses",
                		  "color":"#CC0099"
                		}, 
                		{
                		  "violation":"DefaultPackage",
                		  "color":"#99FF66"
                		}, 		
                		{
                		  "violation":"DataflowAnomalyAnalysis",
                		  "color":"#6E8A6E"
                		},			
                		{
                		  "violation":"AvoidFinalLocalVariable",
                		  "color":"#32007D"
                		}, 
                		{
                		  "violation":"AvoidUsingShortType",
                		  "color":"#0042A3"
                		}, 		
                		{
                	      "violation":"AvoidUsingVolatile",
                		  "color":"#FFFFD6"
                		},		
                		{
                		  "violation":"AvoidPrefixingMethodParameters",
                		  "color":"#666699"
                		},			
                		{
                		  "violation":"AvoidLiteralsInIfCondition",
                		  "color":"#B280B2"
                		}, 
                		{
                	      "violation":"UseConcurrentHashMap",
                		  "color":"#141A0F"
                		}
                ];